[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "MLRun.in"
authors = [{name = "tutor4u", email = "contact@peak-worth.in"}]
dynamic = ["version"]
